In [5]:
import numpy as np 
import pandas as pd

# DataFrames

In [6]:
# from lists

In [7]:
list=[
    ['Jhon',28,'New york',650000],
    ['Don',20,'London',350000],
    ['Mon',27,'Paris',450000],
    ['Fon',18,'New york',250000],
]
cols=["Name","Age","City","Salary"]
pd.DataFrame(list,columns=cols)

   Name  Age      City  Salary
0  Jhon   28  New york  650000
1   Don   20    London  350000
2   Mon   27     Paris  450000
3   Fon   18  New york  250000

In [8]:
# From Dictionaries

In [10]:
data= {
    'Name' : ['Jhon',"Mon","corn","Doreamon"],
    "Age" : [23,23,11,22],
    "Salary" : [2200.0,22233.0,223.300,230000.0],
    "Phone" : [7273142637,[3333333333,4444444444],3234456532,3333222244],
    "City" : ["Nashik","Mumbai","Pune","Japan"],
}
pd.DataFrame(data)

       Name  Age    Salary                     Phone    City
0      Jhon   23    2200.0                7273142637  Nashik
1       Mon   23   22233.0  [3333333333, 4444444444]  Mumbai
2      corn   11     223.3                3234456532    Pune
3  Doreamon   22  230000.0                3333222244   Japan

# Selection and Indexing:

In [14]:
data= {
    'Name' : ['Jhon',"Mon","corn","Doreamon"],
    "Age" : [23,23,11,22],
    "Salary" : [2200.0,22233.0,223.300,230000.0],
    "Phone" : [7273142637,[3333333333,4444444444],3234456532,3333222244],
    "City" : ["Nashik","Mumbai","Pune","Japan"],
}
df=pd.DataFrame(data)
df

       Name  Age    Salary                     Phone    City
0      Jhon   23    2200.0                7273142637  Nashik
1       Mon   23   22233.0  [3333333333, 4444444444]  Mumbai
2      corn   11     223.3                3234456532    Pune
3  Doreamon   22  230000.0                3333222244   Japan

In [17]:
df["Name"] # Selecting perticular column

0        Jhon
1         Mon
2        corn
3    Doreamon
Name: Name, dtype: object

In [16]:
df[["Name","Age"]] #Selecting multiple columns

       Name  Age
0      Jhon   23
1       Mon   23
2      corn   11
3  Doreamon   22

# Creating New Column

In [27]:
df["Designation"] = ["Doctor","Engi.","Doctor","Engi."]
df

       Name  Age    Salary                     Phone    City Designation
0      Jhon   23    2200.0                7273142637  Nashik      Doctor
1       Mon   23   22233.0  [3333333333, 4444444444]  Mumbai       Engi.
2      corn   11     223.3                3234456532    Pune      Doctor
3  Doreamon   22  230000.0                3333222244   Japan       Engi.

# Removing Columns

In [28]:
df.drop("Designation",axis=1) # Just a snapshot To delete it completely we use inplace=True

       Name  Age    Salary                     Phone    City
0      Jhon   23    2200.0                7273142637  Nashik
1       Mon   23   22233.0  [3333333333, 4444444444]  Mumbai
2      corn   11     223.3                3234456532    Pune
3  Doreamon   22  230000.0                3333222244   Japan

In [29]:
df.drop("Designation",axis=1,inplace=True) #Actually deletes the column
df

       Name  Age    Salary                     Phone    City
0      Jhon   23    2200.0                7273142637  Nashik
1       Mon   23   22233.0  [3333333333, 4444444444]  Mumbai
2      corn   11     223.3                3234456532    Pune
3  Doreamon   22  230000.0                3333222244   Japan

# To can select rows

In [31]:
df.loc[0]

Name            Jhon
Age               23
Salary        2200.0
Phone     7273142637
City          Nashik
Name: 0, dtype: object

In [33]:
df.loc[[1,0]]

   Name  Age   Salary                     Phone    City
1   Mon   23  22233.0  [3333333333, 4444444444]  Mumbai
0  Jhon   23   2200.0                7273142637  Nashik

In [34]:
# To select specific portion 
df

       Name  Age    Salary                     Phone    City
0      Jhon   23    2200.0                7273142637  Nashik
1       Mon   23   22233.0  [3333333333, 4444444444]  Mumbai
2      corn   11     223.3                3234456532    Pune
3  Doreamon   22  230000.0                3333222244   Japan

In [37]:
# if we need corn and Mon's Age and salary :
df.loc[[1,2]][['Name','Age','Salary']]

   Name  Age   Salary
1   Mon   23  22233.0
2  corn   11    223.3

# Conditional Selection

In [38]:
# To select Age above 18
df[df["Age"]>18]

       Name  Age    Salary                     Phone    City
0      Jhon   23    2200.0                7273142637  Nashik
1       Mon   23   22233.0  [3333333333, 4444444444]  Mumbai
3  Doreamon   22  230000.0                3333222244   Japan

In [39]:
# For selecting age above 18 and city Japan
df[(df["Age"]>18) & (df["City"]=="Japan")]

       Name  Age    Salary       Phone   City
3  Doreamon   22  230000.0  3333222244  Japan