In [2]:
import numpy as np 
import pandas as pd

# Missing Data

In [5]:
data = {
    'A': [1,23,344,np.nan,np.nan],
    "B": [np.nan ,22,33,44,34.3],
    "C": [22,33,22,4.22,2],
    "D": [np.nan,np.nan,5,np.nan,np.nan],
    "E": [22,33,22,4.22,2],
}
df = pd.DataFrame(data)
df

       A     B      C    D      E
0    1.0   NaN  22.00  NaN  22.00
1   23.0  22.0  33.00  NaN  33.00
2  344.0  33.0  22.00  5.0  22.00
3    NaN  44.0   4.22  NaN   4.22
4    NaN  34.3   2.00  NaN   2.00

In [7]:
df.isna()

       A      B      C      D      E
0  False   True  False   True  False
1  False  False  False   True  False
2  False  False  False  False  False
3   True  False  False   True  False
4   True  False  False   True  False

In [8]:
df.isna().sum()

A    2
B    1
C    0
D    4
E    0
dtype: int64

In [14]:
df.isna().any()

A     True
B     True
C    False
D     True
E    False
dtype: bool

In [15]:
df['A'].isna().any()

np.True_

# Removing Null Values:

In [20]:
df.dropna() # just a snapshot real data not changes till you use inplace=True

       A     B     C    D     E
2  344.0  33.0  22.0  5.0  22.0

In [21]:
df

       A     B      C    D      E
0    1.0   NaN  22.00  NaN  22.00
1   23.0  22.0  33.00  NaN  33.00
2  344.0  33.0  22.00  5.0  22.00
3    NaN  44.0   4.22  NaN   4.22
4    NaN  34.3   2.00  NaN   2.00

# Filling missing values

In [19]:
# Filling with zeros

In [22]:
df.fillna(0)

       A     B      C    D      E
0    1.0   0.0  22.00  0.0  22.00
1   23.0  22.0  33.00  0.0  33.00
2  344.0  33.0  22.00  5.0  22.00
3    0.0  44.0   4.22  0.0   4.22
4    0.0  34.3   2.00  0.0   2.00

In [23]:
# Filling by column wise values

In [24]:
values = {
    "A":100,
    "B":200,
    "C":300,
    "D":400,
    "E":500,
}
df.fillna(value=values)

       A      B      C      D      E
0    1.0  200.0  22.00  400.0  22.00
1   23.0   22.0  33.00  400.0  33.00
2  344.0   33.0  22.00    5.0  22.00
3  100.0   44.0   4.22  400.0   4.22
4  100.0   34.3   2.00  400.0   2.00

In [25]:
# Filling mean

In [29]:
df.fillna(df.mean())

            A       B      C    D      E
0    1.000000  33.325  22.00  5.0  22.00
1   23.000000  22.000  33.00  5.0  33.00
2  344.000000  33.000  22.00  5.0  22.00
3  122.666667  44.000   4.22  5.0   4.22
4  122.666667  34.300   2.00  5.0   2.00