In [1]:
import numpy as np
import pandas as pd

# Phase 1: Subscription Pricing (Series)

In [3]:
# 1. The company offers three plans. Create a Pandas Series representing these prices.
# Use the plan names as the index and the prices as the values.
# Plans (Index): 'Basic', 'Standard', 'Premium'
# Prices (Values): 9.99, 14.99, 19.99

plans = ['Basic', 'Standard', 'Premium']
prices = [9.99, 14.99, 19.99]
series = pd.Series(prices,index=plans)
series

Basic        9.99
Standard    14.99
Premium     19.99
dtype: float64

# Phase 2: User Data Extraction

In [33]:
# Here is the raw data from the engineering team:
streamify_data = {
    'UserID': [101, 102, 103, 104, 105, 106],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
    'Age': [24, 17, 32, 28, np.nan, 15],
    'Plan': ['Premium', 'Basic', 'Standard', 'Premium', 'Basic', 'Standard'],
    'WatchHours': [45.5, np.nan, 22.0, 50.2, 12.5, np.nan],
    'Rating': [5.0, 3.5, np.nan, 4.8, 2.0, 4.0]
}
df = pd.DataFrame(streamify_data)
df

# 2. Convert this dictionary into a Pandas DataFrame called 'df' and display it.

   UserID     Name   Age      Plan  WatchHours  Rating
0     101    Alice  24.0   Premium        45.5     5.0
1     102      Bob  17.0     Basic         NaN     3.5
2     103  Charlie  32.0  Standard        22.0     NaN
3     104    Diana  28.0   Premium        50.2     4.8
4     105      Eve   NaN     Basic        12.5     2.0
5     106    Frank  15.0  Standard         NaN     4.0

# Phase 3: Slicing and Dicing the Data

In [34]:
# 3. The marketing team only wants to see the names and watch hours. 
# Select ONLY the 'Name' and 'WatchHours' columns.
prefered_cols = df[["Name",'WatchHours']]
prefered_cols

      Name  WatchHours
0    Alice        45.5
1      Bob         NaN
2  Charlie        22.0
3    Diana        50.2
4      Eve        12.5
5    Frank         NaN

In [35]:
# 4. We need to target adult users. 
# Filter the DataFrame to show only users whose 'Age' is greater than 18.
df[df["Age"]>18]

   UserID     Name   Age      Plan  WatchHours  Rating
0     101    Alice  24.0   Premium        45.5     5.0
2     103  Charlie  32.0  Standard        22.0     NaN
3     104    Diana  28.0   Premium        50.2     4.8

In [36]:
# 5. EXAM CHALLENGE (Multiple Conditions): 
# Find the highly engaged premium users. 
# Filter the DataFrame for users who are on the 'Premium' plan AND watched more than 40 hours.
df[(df['Plan']=='Premium') & (df['WatchHours']>40)]

   UserID   Name   Age     Plan  WatchHours  Rating
0     101  Alice  24.0  Premium        45.5     5.0
3     104  Diana  28.0  Premium        50.2     4.8

# Phase 4: Column Operations

In [37]:
# 6. The engineering team says 'UserID' is no longer needed for our analysis.
# Drop the 'UserID' column PERMANENTLY from the DataFrame.
df.drop('UserID',axis=1,inplace=True)
df

      Name   Age      Plan  WatchHours  Rating
0    Alice  24.0   Premium        45.5     5.0
1      Bob  17.0     Basic         NaN     3.5
2  Charlie  32.0  Standard        22.0     NaN
3    Diana  28.0   Premium        50.2     4.8
4      Eve   NaN     Basic        12.5     2.0
5    Frank  15.0  Standard         NaN     4.0

In [38]:
# 7. We are running a new campaign. Add a new column called 'EligibleForPromo'.
# Assign the value "Yes" to all rows in this new column for now.
df['EligibleForPromo']='yes'
df

      Name   Age      Plan  WatchHours  Rating EligibleForPromo
0    Alice  24.0   Premium        45.5     5.0              yes
1      Bob  17.0     Basic         NaN     3.5              yes
2  Charlie  32.0  Standard        22.0     NaN              yes
3    Diana  28.0   Premium        50.2     4.8              yes
4      Eve   NaN     Basic        12.5     2.0              yes
5    Frank  15.0  Standard         NaN     4.0              yes

# Phase 5: The Janitor Work

In [39]:
# 8. Let's inspect the damage. 
# Write the code to find the TOTAL number of missing (NaN) values in EACH column.
df.isna().sum()

Name                0
Age                 1
Plan                0
WatchHours          2
Rating              1
EligibleForPromo    0
dtype: int64

In [40]:
# 9. We cannot do math with NaNs! 
# Fill the missing values in the 'WatchHours' column with the MEAN (average) of that column.
# Overwrite the column so the changes are saved.
df['WatchHours'] = df['WatchHours'].fillna(df['WatchHours'].mean())
df

      Name   Age      Plan  WatchHours  Rating EligibleForPromo
0    Alice  24.0   Premium       45.50     5.0              yes
1      Bob  17.0     Basic       32.55     3.5              yes
2  Charlie  32.0  Standard       22.00     NaN              yes
3    Diana  28.0   Premium       50.20     4.8              yes
4      Eve   NaN     Basic       12.50     2.0              yes
5    Frank  15.0  Standard       32.55     4.0              yes

In [43]:
# 10. For the missing 'Age', we cannot guess their age. 
# Drop any ROW that still has a missing value in the 'Age' column.
# Make sure this change is permanent!
df['Age'].dropna(inplace=True)

      Name   Age      Plan  WatchHours  Rating EligibleForPromo
0    Alice  24.0   Premium       45.50     5.0              yes
1      Bob  17.0     Basic       32.55     3.5              yes
2  Charlie  32.0  Standard       22.00     NaN              yes
3    Diana  28.0   Premium       50.20     4.8              yes
4      Eve   NaN     Basic       12.50     2.0              yes
5    Frank  15.0  Standard       32.55     4.0              yes