In [4]:
import numpy as np 
import pandas as pd

# Merging

In [9]:
emps = {
    "id" : [1,2,3,4,5],
    "name" : ['radha','krushna','money','shubhra','varsha'],
    "dept" : ["IT",'Computers','Cloud','Data Science','AI/ML']
}
salaries = {
    "id" : [1,2,3,4,6,7] ,
    "salary" : [10000,20000,30000,40000,50000,600000] ,
    "bonous" : [5000,6000,7000,8000,900,200] ,
}
df1 = pd.DataFrame(emps)
df2 = pd.DataFrame(salaries)

In [15]:
pd.merge(df1,df2,on='id',how='inner') #default is inner which takes only rows that dont have NaN

   id     name          dept  salary  bonous
0   1    radha            IT   10000    5000
1   2  krushna     Computers   20000    6000
2   3    money         Cloud   30000    7000
3   4  shubhra  Data Science   40000    8000

In [16]:
pd.merge(df1,df2,how='outer') # outer takes all rows from both tables and fils with NaN

   id     name          dept    salary  bonous
0   1    radha            IT   10000.0  5000.0
1   2  krushna     Computers   20000.0  6000.0
2   3    money         Cloud   30000.0  7000.0
3   4  shubhra  Data Science   40000.0  8000.0
4   5   varsha         AI/ML       NaN     NaN
5   6      NaN           NaN   50000.0   900.0
6   7      NaN           NaN  600000.0   200.0

In [17]:
pd.merge(df1,df2,how='left') #takes rows only from first table

   id     name          dept   salary  bonous
0   1    radha            IT  10000.0  5000.0
1   2  krushna     Computers  20000.0  6000.0
2   3    money         Cloud  30000.0  7000.0
3   4  shubhra  Data Science  40000.0  8000.0
4   5   varsha         AI/ML      NaN     NaN

In [18]:
pd.merge(df1,df2,how='right') #takes rows only from second table

   id     name          dept  salary  bonous
0   1    radha            IT   10000    5000
1   2  krushna     Computers   20000    6000
2   3    money         Cloud   30000    7000
3   4  shubhra  Data Science   40000    8000
4   6      NaN           NaN   50000     900
5   7      NaN           NaN  600000     200

# Concatination

In [20]:
table1 = {
    'A': ['A1','A2','A3'],
    'B': ['B1','B2','B3'],
    'C': ['C1','C2','C3'],
}
table2 = {
    'A': ['A4','A5','A6'],
    'B': ['B4','B5','B6'],
    'C': ['C4','C5','C6'],
}
df1 = pd.DataFrame(table1)
df2 = pd.DataFrame(table2)
df1,df2

(    A   B   C
 0  A1  B1  C1
 1  A2  B2  C2
 2  A3  B3  C3,
     A   B   C
 0  A4  B4  C4
 1  A5  B5  C5
 2  A6  B6  C6)

In [21]:
pd.concat([df1,df2]) #default axis is 0

    A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6

In [22]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A1  B1  C1  A4  B4  C4
1  A2  B2  C2  A5  B5  C5
2  A3  B3  C3  A6  B6  C6

# Joining

In [25]:
tb1 = {
    "Name" : ['Alice','Bob','Rob']
}
tb2 = {
    "Scores" : [95,99,89]
}
df1 = pd.DataFrame(tb1,index=[1,2,3])
df2 = pd.DataFrame(tb2,index=[2,3,4])
df1,df2

(    Name
 1  Alice
 2    Bob
 3    Rob,
    Scores
 2      95
 3      99
 4      89)

In [28]:
df1.join(df2) # Default how is 'inner'

    Name  Scores
1  Alice     NaN
2    Bob    95.0
3    Rob    99.0

In [29]:
df1.join(df2,how='outer')

    Name  Scores
1  Alice     NaN
2    Bob    95.0
3    Rob    99.0
4    NaN    89.0

In [30]:
df1.join(df2,how='left')

    Name  Scores
1  Alice     NaN
2    Bob    95.0
3    Rob    99.0

In [31]:
df1.join(df2,how='right')

  Name  Scores
2  Bob      95
3  Rob      99
4  NaN      89