In [50]:
import numpy as np
import pandas as pd

In [51]:
data = {
    'category':['A','B','B','A','B'],
    'stores':['s1','s1','s2','s2','s1'],
    'sales':[100,100,200,100,600],
    'quantity':[4,7,0,3,6],
    'date':['12-2024','13-2033','20-2030','10-2012','12-2020']
}
df = pd.DataFrame(data)
df

  category stores  sales  quantity     date
0        A     s1    100         4  12-2024
1        B     s1    100         7  13-2033
2        B     s2    200         0  20-2030
3        A     s2    100         3  10-2012
4        B     s1    600         6  12-2020

# Operations

In [61]:
df.shape

(5, 5)

In [60]:
df.columns

Index(['category', 'stores', 'sales', 'quantity', 'date'], dtype='object')

In [63]:
df.describe

<bound method NDFrame.describe of   category stores  sales  quantity     date
0        A     s1    100         4  12-2024
1        B     s1    100         7  13-2033
2        B     s2    200         0  20-2030
3        A     s2    100         3  10-2012
4        B     s1    600         6  12-2020>

In [62]:
df.describe()

            sales  quantity
count    5.000000  5.000000
mean   220.000000  4.000000
std    216.794834  2.738613
min    100.000000  0.000000
25%    100.000000  3.000000
50%    100.000000  4.000000
75%    200.000000  6.000000
max    600.000000  7.000000

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  5 non-null      object
 1   stores    5 non-null      object
 2   sales     5 non-null      int64
 3   quantity  5 non-null      int64
 4   date      5 non-null      object
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes

In [66]:
df

  category stores  sales  quantity     date
0        A     s1    100         4  12-2024
1        B     s1    100         7  13-2033
2        B     s2    200         0  20-2030
3        A     s2    100         3  10-2012
4        B     s1    600         6  12-2020

In [67]:
df['sales']+100

0    200
1    200
2    300
3    200
4    700
Name: sales, dtype: int64

# applynig functions to dataframe

In [78]:
data = {
    "A":[11,223,12,55,22],
    "B":[33,444,55,22,55],
    "C":[22,11,33,44,22],
}
df = pd.DataFrame(data)
df

     A    B   C
0   11   33  22
1  223  444  11
2   12   55  33
3   55   22  44
4   22   55  22

In [79]:
def square(x):
    return x*x
df['D'] = df['A'].apply(square)
df

     A    B   C      D
0   11   33  22    121
1  223  444  11  49729
2   12   55  33    144
3   55   22  44   3025
4   22   55  22    484

In [80]:
# this can also be done by :
df['E'] = df['A'].apply(lambda x: x*x)
df

     A    B   C      D      E
0   11   33  22    121    121
1  223  444  11  49729  49729
2   12   55  33    144    144
3   55   22  44   3025   3025
4   22   55  22    484    484