In [28]:
#loading the data
import numpy as np 
import pandas as pd

In [29]:
df = pd.read_csv('anime.csv')
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

# make a new column for episode count

In [30]:
for i in [df.loc[x]["Title"] for x in range(5)]:
    print(i)

Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview
Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members
Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members
Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members
Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview

In [31]:
import re
pattern = r'\((\d+)'
df["Episodes"]= df['Title'].apply(lambda x: re.findall(pattern,str(x))[0])
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

# make a new column for time stamp

In [32]:
for i in [df.loc[x]["Title"] for x in range(5)]:
    print(i)

Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview
Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members
Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members
Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members
Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview

In [33]:
dates = df['Title'].str.extract(
    r'([A-Za-z]{3}\s\d{4})\s*-\s*([A-Za-z]{3}\s\d{4})'
)

df['timestamp'] = (
    (pd.to_datetime(dates[1], format='%b %Y').dt.year - 
     pd.to_datetime(dates[0], format='%b %Y').dt.year) * 12
    +
    (pd.to_datetime(dates[1], format='%b %Y').dt.month - 
     pd.to_datetime(dates[0], format='%b %Y').dt.month)
)
df.head()

,Rank,Title,Score,Episodes,timestamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,3

# which anime has the highest score

In [44]:
df[df['Score'] == df['Score'].max()][["Title","Score"]]

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...    9.1

# give me top 5 highest scoring anime

In [42]:
df.nlargest(5,'Score')[['Title','Score']]

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

# which anime has the highest episode count

In [58]:
df[df['Episodes']==df['Episodes'].max()][["Title",'Episodes']]

                                                Title  Episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201

# animes with top 5 episode count

In [59]:
df.nlargest(5,"Episodes")[["Title",'Episodes']]

                                                Title  Episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201
7   Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...       148
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...       110
42  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...        75
24  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...        74

# which is the longest running anime

In [61]:
df.nlargest(1,"timestamp")[["Title",'Episodes']]

                                                Title  Episodes
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...       110